title: Fine Artist & Designer
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.05692104413174093
  brandStrength: 0.490333
  lightness: 0.4338933925610036
  brandColors:
    - '#FFFFFF'
    - '#ABA490'
    - '#716855'
    - '#000175'
    - '#A0DBF2'
  rhythmicContrast: 0.3019399964250624
typography_spectrum: 0.1671429227571934
layout_spectrum: 0.521073253126815
name: conormcguire.com
